# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainingGrounds_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trainingGrounds_Dialog(object):
    def setupUi(self, trainingGrounds_Dialog):
        trainingGrounds_Dialog.setObjectName("trainingGrounds_Dialog")
        trainingGrounds_Dialog.resize(526, 360)
        self.formLayout = QtWidgets.QFormLayout(trainingGrounds_Dialog)
        self.formLayout.setObjectName("formLayout")
        self.roster_tableWidget = QtWidgets.QTableWidget(trainingGrounds_Dialog)
        self.roster_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.roster_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.roster_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.roster_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.roster_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.roster_tableWidget.setColumnCount(5)
        self.roster_tableWidget.setObjectName("roster_tableWidget")
        self.roster_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.roster_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.roster_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.roster_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.roster_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.roster_tableWidget.setHorizontalHeaderItem(4, item)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.roster_tableWidget)
        self.add_pushButton = QtWidgets.QPushButton(trainingGrounds_Dialog)
        self.add_pushButton.setObjectName("add_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.add_pushButton)
        self.remove_pushButton = QtWidgets.QPushButton(trainingGrounds_Dialog)
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remove_pushButton)
        self.party_tableWidget = QtWidgets.QTableWidget(trainingGrounds_Dialog)
        self.party_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.party_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.party_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.party_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.party_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.party_tableWidget.setColumnCount(5)
        self.party_tableWidget.setObjectName("party_tableWidget")
        self.party_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(4, item)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.party_tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(trainingGrounds_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(trainingGrounds_Dialog)
        self.buttonBox.accepted.connect(trainingGrounds_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(trainingGrounds_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(trainingGrounds_Dialog)

    def retranslateUi(self, trainingGrounds_Dialog):
        _translate = QtCore.QCoreApplication.translate
        trainingGrounds_Dialog.setWindowTitle(_translate("trainingGrounds_Dialog", "Training Grounds"))
        item = self.roster_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("trainingGrounds_Dialog", "Name"))
        item = self.roster_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("trainingGrounds_Dialog", "Class/Race"))
        item = self.roster_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("trainingGrounds_Dialog", "AC"))
        item = self.roster_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("trainingGrounds_Dialog", "HP"))
        item = self.roster_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("trainingGrounds_Dialog", "Status"))
        self.add_pushButton.setText(_translate("trainingGrounds_Dialog", ">>"))
        self.remove_pushButton.setText(_translate("trainingGrounds_Dialog", "<<"))
        item = self.party_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("trainingGrounds_Dialog", "Name"))
        item = self.party_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("trainingGrounds_Dialog", "Class/Race"))
        item = self.party_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("trainingGrounds_Dialog", "AC"))
        item = self.party_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("trainingGrounds_Dialog", "HP"))
        item = self.party_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("trainingGrounds_Dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trainingGrounds_Dialog = QtWidgets.QDialog()
    ui = Ui_trainingGrounds_Dialog()
    ui.setupUi(trainingGrounds_Dialog)
    trainingGrounds_Dialog.show()
    sys.exit(app.exec_())
