# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maze_QFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mazeFrame(object):
    def setupUi(self, mazeFrame):
        mazeFrame.setObjectName("mazeFrame")
        mazeFrame.resize(494, 365)
        mazeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        mazeFrame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.retranslateUi(mazeFrame)
        QtCore.QMetaObject.connectSlotsByName(mazeFrame)

    def retranslateUi(self, mazeFrame):
        _translate = QtCore.QCoreApplication.translate
        mazeFrame.setWindowTitle(_translate("mazeFrame", "Maze"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mazeFrame = QtWidgets.QFrame()
    ui = Ui_mazeFrame()
    ui.setupUi(mazeFrame)
    mazeFrame.show()
    sys.exit(app.exec_())
