# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monsters_select_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_monsters_select_Dialog(object):
    def setupUi(self, monsters_select_Dialog):
        monsters_select_Dialog.setObjectName("monsters_select_Dialog")
        monsters_select_Dialog.resize(416, 103)
        self.gridLayout = QtWidgets.QGridLayout(monsters_select_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.monsters_tableWidget = QtWidgets.QTableWidget(monsters_select_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monsters_tableWidget.sizePolicy().hasHeightForWidth())
        self.monsters_tableWidget.setSizePolicy(sizePolicy)
        self.monsters_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.monsters_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.monsters_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.monsters_tableWidget.setColumnCount(2)
        self.monsters_tableWidget.setObjectName("monsters_tableWidget")
        self.monsters_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.monsters_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monsters_tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.monsters_tableWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(monsters_select_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)

        self.retranslateUi(monsters_select_Dialog)
        self.buttonBox.accepted.connect(monsters_select_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(monsters_select_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(monsters_select_Dialog)

    def retranslateUi(self, monsters_select_Dialog):
        _translate = QtCore.QCoreApplication.translate
        monsters_select_Dialog.setWindowTitle(_translate("monsters_select_Dialog", "Dialog"))
        item = self.monsters_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("monsters_select_Dialog", "Monster"))
        item = self.monsters_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("monsters_select_Dialog", "Count"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    monsters_select_Dialog = QtWidgets.QDialog()
    ui = Ui_monsters_select_Dialog()
    ui.setupUi(monsters_select_Dialog)
    monsters_select_Dialog.show()
    sys.exit(app.exec_())
