# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'party_select_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_party_select_Dialog(object):
    def setupUi(self, party_select_Dialog):
        party_select_Dialog.setObjectName("party_select_Dialog")
        party_select_Dialog.resize(664, 202)
        self.gridLayout = QtWidgets.QGridLayout(party_select_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.party_tableWidget = QtWidgets.QTableWidget(party_select_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.party_tableWidget.sizePolicy().hasHeightForWidth())
        self.party_tableWidget.setSizePolicy(sizePolicy)
        self.party_tableWidget.setMaximumSize(QtCore.QSize(551, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.party_tableWidget.setFont(font)
        self.party_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.party_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.party_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.party_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.party_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.party_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.party_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.party_tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.party_tableWidget.setColumnCount(7)
        self.party_tableWidget.setObjectName("party_tableWidget")
        self.party_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.party_tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.party_tableWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(party_select_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)

        self.retranslateUi(party_select_Dialog)
        self.buttonBox.accepted.connect(party_select_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(party_select_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(party_select_Dialog)

    def retranslateUi(self, party_select_Dialog):
        _translate = QtCore.QCoreApplication.translate
        party_select_Dialog.setWindowTitle(_translate("party_select_Dialog", "Dialog"))
        item = self.party_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("party_select_Dialog", "Name"))
        item = self.party_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("party_select_Dialog", "Class"))
        item = self.party_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("party_select_Dialog", "Race"))
        item = self.party_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("party_select_Dialog", "AC"))
        item = self.party_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("party_select_Dialog", "HP"))
        item = self.party_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("party_select_Dialog", "HP Max"))
        item = self.party_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("party_select_Dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    party_select_Dialog = QtWidgets.QDialog()
    ui = Ui_party_select_Dialog()
    ui.setupUi(party_select_Dialog)
    party_select_Dialog.show()
    sys.exit(app.exec_())
