# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_Grounds_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainingGrounds_Dialog(object):
    def setupUi(self, TrainingGrounds_Dialog):
        TrainingGrounds_Dialog.setObjectName("TrainingGrounds_Dialog")
        TrainingGrounds_Dialog.resize(249, 292)
        TrainingGrounds_Dialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(TrainingGrounds_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nav_frame = QtWidgets.QFrame(TrainingGrounds_Dialog)
        self.nav_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nav_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nav_frame.setObjectName("nav_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.nav_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.classChangeButton = QtWidgets.QPushButton(self.nav_frame)
        self.classChangeButton.setEnabled(False)
        self.classChangeButton.setObjectName("classChangeButton")
        self.gridLayout.addWidget(self.classChangeButton, 5, 0, 1, 1)
        self.renameCharButton = QtWidgets.QPushButton(self.nav_frame)
        self.renameCharButton.setEnabled(False)
        self.renameCharButton.setObjectName("renameCharButton")
        self.gridLayout.addWidget(self.renameCharButton, 4, 0, 1, 1)
        self.randomCharButton = QtWidgets.QPushButton(self.nav_frame)
        self.randomCharButton.setObjectName("randomCharButton")
        self.gridLayout.addWidget(self.randomCharButton, 1, 0, 1, 1)
        self.deleteCharButton = QtWidgets.QPushButton(self.nav_frame)
        self.deleteCharButton.setEnabled(False)
        self.deleteCharButton.setObjectName("deleteCharButton")
        self.gridLayout.addWidget(self.deleteCharButton, 3, 0, 1, 1)
        self.newCharButton = QtWidgets.QPushButton(self.nav_frame)
        self.newCharButton.setEnabled(False)
        self.newCharButton.setObjectName("newCharButton")
        self.gridLayout.addWidget(self.newCharButton, 0, 0, 1, 1)
        self.charStatusButton = QtWidgets.QPushButton(self.nav_frame)
        self.charStatusButton.setEnabled(False)
        self.charStatusButton.setObjectName("charStatusButton")
        self.gridLayout.addWidget(self.charStatusButton, 2, 0, 1, 1)
        self.castleButton = QtWidgets.QPushButton(self.nav_frame)
        self.castleButton.setObjectName("castleButton")
        self.gridLayout.addWidget(self.castleButton, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.nav_frame, 0, 0, 1, 1)

        self.retranslateUi(TrainingGrounds_Dialog)
        QtCore.QMetaObject.connectSlotsByName(TrainingGrounds_Dialog)

    def retranslateUi(self, TrainingGrounds_Dialog):
        _translate = QtCore.QCoreApplication.translate
        TrainingGrounds_Dialog.setWindowTitle(_translate("TrainingGrounds_Dialog", "Training Grounds"))
        self.classChangeButton.setText(_translate("TrainingGrounds_Dialog", "Change a Character\'s Class"))
        self.renameCharButton.setText(_translate("TrainingGrounds_Dialog", "Rename a Character"))
        self.randomCharButton.setText(_translate("TrainingGrounds_Dialog", "Create a Random Character"))
        self.deleteCharButton.setText(_translate("TrainingGrounds_Dialog", "Delete a Character"))
        self.newCharButton.setText(_translate("TrainingGrounds_Dialog", "Create a New Character"))
        self.charStatusButton.setText(_translate("TrainingGrounds_Dialog", "Character status"))
        self.castleButton.setText(_translate("TrainingGrounds_Dialog", "Return to Castle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainingGrounds_Dialog = QtWidgets.QDialog()
    ui = Ui_TrainingGrounds_Dialog()
    ui.setupUi(TrainingGrounds_Dialog)
    TrainingGrounds_Dialog.show()
    sys.exit(app.exec_())
